version: '3.6'
services:

  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: personaltools
      POSTGRES_PASSWORD: personaltools
      POSTGRES_DB: personaltools

