# Generated by Django 6.1 on 2026-08-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
